
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 30 00:13:38 CST 2019
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_IZQ = 3;
  public static final int LLAVE_DER = 4;
  public static final int PTCOMA = 2;
  public static final int EOF = 0;
  public static final int T_CHAR = 6;
  public static final int error = 1;
  public static final int T_BOOL = 7;
  public static final int IDENTIFICADOR = 8;
  public static final int T_INT = 5;
}

